remote = false
callback_url = "http://localhost:3000/api/status-update"

[models]

# [models.one]
# name = "EleutherAI/pythia-70m-deduped"
# chat = false

# [models.one.rename]
# gpt_neox = "model"
# embed_out = "lm_head"
# final_layer_norm = "ln_f"

[models.one]
name = "Qwen/Qwen3-0.6B"
chat = false

[models.one.rename]
embed_out = "lm_head"
norm = "ln_f"