[project]
name = "interp-workbench"
version = "0.1.0"
description = "Interpretability workbench"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.115.6",
    "toml>=0.10.2",
    "uvicorn>=0.32.1",
    "httpx",
    "aws-cdk-lib>=2.0.0",
    "constructs>=10.0.0",
    "python-dotenv>=1.0.1",
    "nnsight>=0.4.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["workbench"]
