[project]
name = "interp-workbench"
version = "0.1.0"
description = "Interpretability workbench"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.115.6",
    "python-dotenv>=1.0.1",
    "nnsight>=0.4.7",
    "modal>=0.65.66",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["workbench"]
