# STANDARD NAMING:
# model.layers.i.attn
# model.layers.i.mlp
# model.ln_f
# model.lm_head

remote = false

[models]

[models.one]
name = "EleutherAI/pythia-70m-deduped"
chat = false

[models.one.rename]
gpt_neox = "model"
embed_out = "lm_head"
final_layer_norm = "ln_f"

[models.two]
name = "Qwen/Qwen3-0.6B"
chat = false

[models.two.rename]
embed_out = "lm_head"
norm = "ln_f"